/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-fixed": "#e9e2d4",
        "inverse-primary": "#f7bb75",
        "tertiary": "#625e54",
        "on-tertiary": "#ffffff",
        "danger": "#A24E43",
        "on-primary-container": "#442800",
        "on-surface": "#1c1c18",
        "on-background": "#1c1c18",
        "background": "#fdf9f2",
        "on-error": "#ffffff",
        "outline-variant": "#d4c4b4",
        "surface-container": "#f1ede6",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#663e00",
        "secondary-container": "#dbe3f3",
        "surface-container-highest": "#e6e2db",
        "on-secondary-fixed-variant": "#3f4754",
        "on-surface-variant": "#504539",
        "on-error-container": "#93000a",
        "glass-start": "#EDE7DD",
        "surface-dim": "#dddad3",
        "outline": "#827567",
        "surface-tint": "#815518",
        "primary-fixed-dim": "#f7bb75",
        "error-container": "#ffdad6",
        "on-secondary-fixed": "#141c27",
        "on-tertiary-fixed": "#1e1b13",
        "on-tertiary-fixed-variant": "#4a463d",
        "surface-variant": "#e6e2db",
        "error": "#ba1a1a",
        "ink-700": "#514D45",
        "primary-fixed": "#ffddb9",
        "ink-900": "#2B2924",
        "surface-container-lowest": "#ffffff",
        "success": "#5C7A5E",
        "tertiary-fixed-dim": "#ccc6b9",
        "sent": "#4C6A82",
        "on-primary-fixed": "#2b1700",
        "secondary": "#575f6c",
        "primary-container": "#c08b4a",
        "on-tertiary-container": "#312e25",
        "inverse-surface": "#31302c",
        "glass-end": "#D9D2C4",
        "surface": "#fdf9f2",
        "pending": "#C4823E",
        "inverse-on-surface": "#f4f0e9",
        "tertiary-container": "#9a9589",
        "primary": "#815518",
        "secondary-fixed-dim": "#bfc7d6",
        "on-secondary-container": "#5d6572",
        "surface-container-low": "#f7f3ec",
        "secondary-fixed": "#dbe3f3",
        "surface-container-high": "#ebe8e1",
        "on-primary": "#ffffff",
        "surface-bright": "#fdf9f2",
        "deep-navy": "#1A2332"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "8px",
        "margin-desktop": "64px",
        "container-max": "1120px",
        "gutter": "24px",
        "margin-mobile": "20px"
      },
      fontFamily: {
        "display-lg": ["\"Source Serif 4\"", "serif"],
        "body-lg": ["\"Atkinson Hyperlegible Next\"", "sans-serif"],
        "body-md": ["\"Atkinson Hyperlegible Next\"", "sans-serif"],
        "label-lg": ["\"Atkinson Hyperlegible Next\"", "sans-serif"],
        "headline-lg-mobile": ["\"Source Serif 4\"", "serif"],
        "button": ["\"Atkinson Hyperlegible Next\"", "sans-serif"],
        "headline-lg": ["\"Source Serif 4\"", "serif"]
      }
    },
  },
  plugins: [],
}
